import type {
  User,
  InstagramAccount,
  VaultItem,
  ScheduledPost,
  GhostModeConfig,
  MomentumMetrics,
  AnalyticsData,
  AISuggestion,
  SurvivalLog,
  Notification,
} from "@/types";

export const mockUser: User = {
  id: "usr_1",
  name: "Alex Morgan",
  email: "alex@ghostflow.ai",
  avatarUrl: "/avatar.png",
  plan: "creator_pro",
  instagramConnected: true,
  instagramHandle: "@alexcreates",
  createdAt: "2025-09-15",
};

export const mockInstagram: InstagramAccount = {
  id: "ig_1",
  handle: "@alexcreates",
  avatarUrl: "/avatar.png",
  followers: 42800,
  following: 1250,
  postsCount: 847,
  isConnected: true,
  lastSyncAt: "2025-12-20T10:30:00Z",
};

export const mockVaultItems: VaultItem[] = [
  {
    id: "v1",
    type: "image",
    title: "Sunset Motivation",
    caption: "Every sunset is a reminder that endings can be beautiful too. 🌅 #motivation #sunset #mindset",
    tags: ["motivational", "evergreen"],
    thumbnailUrl: "https://picsum.photos/seed/v1/400/400",
    createdAt: "2025-11-01",
    usedCount: 3,
    performanceScore: 92,
    isEvergreen: true,
  },
  {
    id: "v2",
    type: "reel",
    title: "Morning Routine Tips",
    caption: "My 5 AM routine that changed everything. Save this for later! ⏰ #morningroutine #productivity",
    tags: ["educational", "viral"],
    thumbnailUrl: "https://picsum.photos/seed/v2/400/400",
    createdAt: "2025-11-05",
    usedCount: 1,
    performanceScore: 88,
    isEvergreen: true,
  },
  {
    id: "v3",
    type: "carousel",
    title: "Growth Hacks 2025",
    caption: "10 Instagram growth hacks that actually work in 2025 🚀 Swipe to learn → #growthhacks #instagram",
    tags: ["educational", "evergreen"],
    thumbnailUrl: "https://picsum.photos/seed/v3/400/400",
    createdAt: "2025-11-10",
    usedCount: 5,
    performanceScore: 95,
    isEvergreen: true,
  },
  {
    id: "v4",
    type: "image",
    title: "Behind The Scenes",
    caption: "POV: You finally see what goes on behind the camera 📸 #bts #creatorlife",
    tags: ["personal", "trending"],
    thumbnailUrl: "https://picsum.photos/seed/v4/400/400",
    createdAt: "2025-11-15",
    usedCount: 0,
    performanceScore: 72,
    isEvergreen: false,
  },
  {
    id: "v5",
    type: "reel",
    title: "Meme Compilation",
    caption: "When your queue runs out and you haven't planned anything 💀 #creatormemes #relatable",
    tags: ["meme", "viral"],
    thumbnailUrl: "https://picsum.photos/seed/v5/400/400",
    createdAt: "2025-11-20",
    usedCount: 2,
    performanceScore: 96,
    isEvergreen: false,
  },
  {
    id: "v6",
    type: "image",
    title: "Workspace Setup",
    caption: "Upgraded the setup. New year, new goals. What do you think? 🖥️ #workspace #setup #creator",
    tags: ["personal", "trending"],
    thumbnailUrl: "https://picsum.photos/seed/v6/400/400",
    createdAt: "2025-11-25",
    usedCount: 1,
    performanceScore: 81,
    isEvergreen: false,
  },
  {
    id: "v7",
    type: "carousel",
    title: "Content Calendar Template",
    caption: "Free content calendar template for creators 📅 Save + Share! #contentcalendar #template #free",
    tags: ["educational", "evergreen", "viral"],
    thumbnailUrl: "https://picsum.photos/seed/v7/400/400",
    createdAt: "2025-12-01",
    usedCount: 7,
    performanceScore: 98,
    isEvergreen: true,
  },
  {
    id: "v8",
    type: "reel",
    title: "Day In My Life",
    caption: "A day in the life of a full-time content creator ☀️🌙 #dayinmylife #vlog",
    tags: ["personal", "trending"],
    thumbnailUrl: "https://picsum.photos/seed/v8/400/400",
    createdAt: "2025-12-05",
    usedCount: 0,
    performanceScore: 68,
    isEvergreen: false,
  },
];

export const mockScheduledPosts: ScheduledPost[] = [
  {
    id: "sp1",
    vaultItemId: "v1",
    caption: "Every sunset is a reminder that endings can be beautiful too. 🌅",
    hashtags: ["motivation", "sunset", "mindset"],
    scheduledAt: "2025-12-21T09:00:00Z",
    status: "scheduled",
    type: "image",
    thumbnailUrl: "https://picsum.photos/seed/v1/400/400",
  },
  {
    id: "sp2",
    vaultItemId: "v2",
    caption: "My 5 AM routine that changed everything. Save this for later! ⏰",
    hashtags: ["morningroutine", "productivity"],
    scheduledAt: "2025-12-21T18:00:00Z",
    status: "scheduled",
    type: "reel",
    thumbnailUrl: "https://picsum.photos/seed/v2/400/400",
  },
  {
    id: "sp3",
    vaultItemId: "v3",
    caption: "10 Instagram growth hacks that actually work in 2025 🚀",
    hashtags: ["growthhacks", "instagram", "tips"],
    scheduledAt: "2025-12-22T12:00:00Z",
    status: "scheduled",
    type: "carousel",
    thumbnailUrl: "https://picsum.photos/seed/v3/400/400",
  },
  {
    id: "sp4",
    vaultItemId: "v5",
    caption: "When your queue runs out and you haven't planned anything 💀",
    hashtags: ["creatormemes", "relatable"],
    firstComment: "Tag a creator who needs GhostFlow 👻",
    scheduledAt: "2025-12-23T10:00:00Z",
    status: "scheduled",
    type: "reel",
    thumbnailUrl: "https://picsum.photos/seed/v5/400/400",
  },
  {
    id: "sp5",
    vaultItemId: "v7",
    caption: "Free content calendar template for creators 📅 Save + Share!",
    hashtags: ["contentcalendar", "template", "free"],
    scheduledAt: "2025-12-24T14:00:00Z",
    status: "scheduled",
    type: "carousel",
    thumbnailUrl: "https://picsum.photos/seed/v7/400/400",
  },
];

export const mockGhostModeConfig: GhostModeConfig = {
  enabled: true,
  inactivityThresholdDays: 3,
  emergencySurvivalMode: true,
  aiFallbackBehavior: "remix_captions",
  maxSurvivalPostsPerWeek: 5,
  preserveHashtags: true,
  notifyOnActivation: true,
};

export const mockMomentum: MomentumMetrics = {
  consistencyScore: 87,
  inactivityRisk: "low",
  momentumStability: 92,
  queueHealth: 78,
  queueLifespanDays: 12,
  postsThisWeek: 5,
  postsLastWeek: 6,
  survivalActivations: 2,
  streakDays: 34,
};

export const mockAnalytics: AnalyticsData[] = [
  { date: "Mon", posts: 2, engagement: 4.2, reach: 12500, momentum: 85 },
  { date: "Tue", posts: 1, engagement: 3.8, reach: 9800, momentum: 82 },
  { date: "Wed", posts: 2, engagement: 5.1, reach: 15200, momentum: 88 },
  { date: "Thu", posts: 1, engagement: 4.5, reach: 11300, momentum: 86 },
  { date: "Fri", posts: 3, engagement: 6.2, reach: 18700, momentum: 91 },
  { date: "Sat", posts: 2, engagement: 5.8, reach: 16400, momentum: 90 },
  { date: "Sun", posts: 1, engagement: 4.0, reach: 10100, momentum: 84 },
];

export const mockWeeklyAnalytics: AnalyticsData[] = [
  { date: "W1", posts: 10, engagement: 4.5, reach: 45000, momentum: 82 },
  { date: "W2", posts: 12, engagement: 5.2, reach: 58000, momentum: 87 },
  { date: "W3", posts: 8, engagement: 4.1, reach: 38000, momentum: 78 },
  { date: "W4", posts: 14, engagement: 5.8, reach: 67000, momentum: 92 },
];

export const mockAISuggestions: AISuggestion[] = [
  {
    id: "ai1",
    type: "resurrect",
    title: "Resurrect: Content Calendar Template",
    description:
      "This carousel had a 98% performance score and hasn't been reposted in 20 days. Perfect for re-engagement.",
    confidence: 95,
    vaultItemId: "v7",
    suggestedCaption:
      "Still the most saved post this year 📅 Your free content calendar template — updated for 2026! #contentcalendar",
    createdAt: "2025-12-20T08:00:00Z",
  },
  {
    id: "ai2",
    type: "remix",
    title: "Caption Remix: Morning Routine",
    description:
      "AI generated a fresh caption for your morning routine reel to re-engage your audience.",
    confidence: 88,
    vaultItemId: "v2",
    suggestedCaption:
      "The routine that turns chaos into clarity. 5 AM hits different when you have a system. ⏰✨ #routine",
    createdAt: "2025-12-20T08:15:00Z",
  },
  {
    id: "ai3",
    type: "repost",
    title: "Repost: Growth Hacks Carousel",
    description:
      "High-performing evergreen content. Your audience has grown 12% since last post — new followers haven't seen this.",
    confidence: 91,
    vaultItemId: "v3",
    createdAt: "2025-12-20T08:30:00Z",
  },
  {
    id: "ai4",
    type: "new_content",
    title: "Trending Topic: Year in Review",
    description:
      "Year-in-review content is trending. Create a 2025 highlights carousel for high engagement.",
    confidence: 82,
    createdAt: "2025-12-20T09:00:00Z",
  },
];

export const mockSurvivalLogs: SurvivalLog[] = [
  {
    id: "sl1",
    action: "Ghost Mode Activated",
    description: "3 days of inactivity detected. Ghost Mode auto-activated survival posting.",
    timestamp: "2025-12-15T00:00:00Z",
    status: "success",
  },
  {
    id: "sl2",
    action: "Survival Post Published",
    description: 'Evergreen content "Growth Hacks 2025" was reposted with remixed caption.',
    timestamp: "2025-12-15T09:00:00Z",
    status: "success",
    postId: "sp_auto_1",
  },
  {
    id: "sl3",
    action: "Caption Remixed",
    description: "AI generated fresh caption for morning routine reel to avoid duplicate detection.",
    timestamp: "2025-12-16T09:00:00Z",
    status: "success",
  },
  {
    id: "sl4",
    action: "Queue Health Warning",
    description: "Queue health dropped below 30%. Survival queue activated as backup.",
    timestamp: "2025-12-17T12:00:00Z",
    status: "warning",
  },
  {
    id: "sl5",
    action: "Momentum Protected",
    description: "Account momentum maintained at 85+ during 5-day absence. No algorithmic penalty detected.",
    timestamp: "2025-12-18T00:00:00Z",
    status: "success",
  },
  {
    id: "sl6",
    action: "Content Resurrection",
    description: "Top-performing carousel resurrected for new audience segment (12% new followers).",
    timestamp: "2025-12-19T10:00:00Z",
    status: "success",
    postId: "sp_auto_3",
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "n1",
    type: "success",
    title: "Ghost Mode Active",
    message: "Your account is being protected by Ghost Mode. 3 survival posts queued.",
    timestamp: "2025-12-20T10:00:00Z",
    read: false,
  },
  {
    id: "n2",
    type: "warning",
    title: "Queue Running Low",
    message: "Your posting queue has only 5 posts remaining. Consider adding more content to your vault.",
    timestamp: "2025-12-19T15:00:00Z",
    read: false,
  },
  {
    id: "n3",
    type: "info",
    title: "AI Suggestion Available",
    message: "GhostFlow AI found 3 top-performing posts ready for resurrection.",
    timestamp: "2025-12-19T09:00:00Z",
    read: true,
  },
];
